services:
  mongo:
    image: mongo:7
    container_name: kaiburr-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kaiburr-task-manager
    environment:
      - MONGODB_URI=mongodb://mongo:27017/kaiburr
    ports:
      - "8081:8080"
    depends_on:
      - mongo

volumes:
  mongo-data:


